# Generated by Django 5.2.8 on 2025-12-27 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SectionName', models.CharField(max_length=3)),
                ('Sec_Teacher', models.CharField(max_length=200)),
                ('S_Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=200)),
                ('StudentID', models.IntegerField(unique=True)),
                ('Sec_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clgforms.section')),
            ],
        ),
    ]
