# Generated by Django 4.1.6 on 2023-03-10 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='Token',
            new_name='token',
        ),
    ]
