# Generated by Django 5.2.9 on 2026-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('Pno', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('Description', models.TextField(default='Friends')),
            ],
        ),
    ]
